#!/bin/bash

set -ueo "pipefail"

cd "/mnt/build"

declare action="${1}"

case "${action}" in
  "build-opencv")
      sudo pacman -Sy
      asp checkout "opencv"
      cd "opencv/trunk"
      makepkg \
        --syncdeps \
        --rmdeps \
        --noconfirm
    ;;

esac
