/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package radium226.swig;

public class globalJNI {
  public final static native void Showcase_displayImageUsingOpenCVInCpp(long jarg1);
  public final static native void Showcase_displayImageUsingDLibInCpp(long jarg1);
  public final static native void Showcase_drawCircleImageUsingOpenCVInCpp(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, long jarg7);
  public final static native void Showcase_drawCircleImageUsingDLibInCpp(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, long jarg7);
  public final static native long new_Showcase();
  public final static native void delete_Showcase(long jarg1);
}
